# Generated by Django 5.0.1 on 2024-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile/default-picture.png', upload_to='profile/'),
        ),
    ]
