# Generated by Django 5.0.1 on 2024-04-28 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_whislist'),
    ]

    operations = [
        migrations.AddField(
            model_name='whislist',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
