# Generated by Django 5.0.1 on 2024-04-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_whislist_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whislist',
            new_name='Wishlist',
        ),
    ]
