# Generated by Django 5.0.1 on 2024-05-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_cart_quantity_alter_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
