# Generated by Django 5.0.1 on 2024-05-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_details',
        ),
    ]
